
defaultEntryPoints = ["http","https"]

[entryPoints]
    [entryPoints.dashboard]
        address = ":8080"
        [entryPoints.dashboard.auth]
            [entryPoints.dashboard.auth.basic]
                user = ["admin:$apr1$GKQ0Lhin$yvDfwhv/uCq5iKppgWq7h1"]
    
#Automatically redirect all of the traffic on port 80 to 443
    [entryPoints.http]
        address = ":80"
        [entryPoints.http.redirect]
            entryPoint = "https"
    [entryPoints.https]
        address = ":443"
            [entryPoints.https.tls]

[api]
    entrypoint = "dashboard"

## Protocol used to communicate with Lets Encrypt
[acme]
email = "dalyna.pak@hotmail.fr"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
    entryPoint = "http"

#Enable Traefik to act as a proxy in front of Docker containers
[docker]
    domain = [dapak]
    watch = true
    network = "web"
